#!/usr/bin/python
import sys
import numpy

#mine
import fixposcarscale
from paircor import paircor #paircor(atoms,inloop=0,cutoff=10.0,nbins=1000):

def usage():
    print "Usage:"
    print sys.argv[0]+" <OUTCAR file> <start config (0)> <final config (last)>"

if len(sys.argv)<4:
    usage()
    exit(0)

outcarfile=sys.argv[1]
startcfg=int(sys.argv[2])
finalcfg=int(sys.argv[3])

outcar = open("%s/OUTCAR"%indir,"r").readlines()

head=poscar.readline().strip()
poscar.readline()
v1=map(float,poscar.readline().split())
v2=map(float,poscar.readline().split())
v3=map(float,poscar.readline().split())
nums=poscar.readline()
Natoms=sum(map(int,nums.split()))
poscar.close()

wdat="%s (This poscar generated by %s, from %s/OUTCAR)\n"%(head,sys.argv[0],sys.argv[1])
wdat+="1.0\n"

count=-1
while True:
    #Start a new configuration
    line=outcar.readline()
    if len(line)==0:
        break
    if "FORCE on cell" in line:
        count+=1
        while True:
            line=outcar.readline()
            if "direct lattice vectors" in line:
                line=outcar.readline()
                v1=" ".join(line.split()[0:3])
                line=outcar.readline()
                v2=" ".join(line.split()[0:3])
                line=outcar.readline()
                v3=" ".join(line.split()[0:3])
                break

        while True:
            line=outcar.readline()
            if "POSITION" in line:
                outcar.readline()
                posi=list()
                while True:
                    line=outcar.readline()
                    posi.append(" ".join(line.split()[0:3]))
                    if len(posi)==Natoms:
                        break
                break
        if count==wantconfig:
            break

#Generate the rest of the poscar and write it out, make sure to correct for direct output
if count>=0:
    wdat+=v1+"\n"
    wdat+=v2+"\n"
    wdat+=v3+"\n"
    wdat+=nums
    wdat+="Direct\n"
    for i in posi:
        wdat+=i+"\n"
    open(outpos,"w").writelines(wdat)
    fixposcarscale.fixposcarscale(outpos)
else:
    raise IOError("Unable to find desired POSCAR in OUTCAR.")
