#!/usr/bin/python

import sys
from math import *
from scipy import array,zeros
import pylab as pl
#mine
from meanSquareDist import meanSquareDistRefAtom
from orderParams import tetrahedral
import outcarIO
#msdIO

#Calculates mean squared distance

def usage():
    print "Usage: %s <Outcar> <Reference Config #> <opt:-tet>"%sys.argv[0].split("/")[-1]
    print "-tet flag enables per atom tetrahedral order parameter to be calculated as well"

def outcarMeanSquareDisplaceAtom(outcarFile,refStructure=None):
    outcar=open(outcarFile,"r")
    atoms=list() #atoms[time][atom]

    #Grab ion types
    while True:
        line=outcar.readline()
        if "ions per type" in line:
            break
    atypes=map(int,line.split("=")[1].split())
    Natom=sum(atypes)

    #Grab basis vectors
    while True:
        line=outcar.readline()
        if "direct lattice vectors" in line:
            break
    basis=array([map(float,outcar.readline().split()[:3]) for i in range(3)])
    lengths=array([basis[0][0],basis[1][1],basis[2][2]])

    #Grab atom positions
    count=0
    posit=False
    for line in outcar:
        if posit:
            if "--" in line:
                if len(a)==0:
                    continue
                else:
                    #Analysis
                    atoms.append(array(a))
                    posit=False
            else:
                a.append(map(float,line.split()[:3]))
        elif "POSITION" in line:
            a=list()
            posit=True
            count+=1
    atoms=array(atoms)
    Ntime=len(atoms)

    if refStructure==None:
        delT,msdPerAtom=meanSquareDistRefAtom(atoms,0,Natom,Ntime,lengths)
    elif refStructure > Ntime:
        print "%d requested but %d structures max"%(refStructure,Ntime)
    else:
        delT,msdPerAtom=meanSquareDistRefAtom(atoms,refStructure,Natom,Ntime,lengths)

    return delT,msdPerAtom


if __name__=="__main__":
    if len(sys.argv)<2:
        usage()
        exit(0)
    
    tetFlag=False
    for i in range(len(sys.argv)):
        if sys.argv[i] in ["-tet","-TET","-Tet"]:
            tetFlag=True
            sys.argv.pop(i)

    outcarFile=sys.argv[1]
    try:
        num=sys.argv[1].split("_")[1]
    except IndexError:
        num=None

    refStructure=None
    if len(sys.argv)==3:
        refStructure=int(sys.argv[2])

    delT,msdAtom=outcarMeanSquareDisplaceAtom(outcarFile,refStructure)
    
    if tetFlag:
        dummy,dummy,basis,atoms,dummy,types = outcarIO.outcarReadConfig(outcarFile,wantconfig=-1)
        tets,rcut=tetrahedral(atoms,basis)

    wFile = open(outcarFile+".MSDatom","w")

    wFile.write("#File generated by %s\n"%sys.argv[0].split("/")[-1])
    wFile.write("#%d atoms, %5.5f timestep size, %d number of steps\n"%(len(msdAtom),delT[0],len(delT)))
    if tetFlag:
        wFile.write("msd$(AA^2)$ tetra\n")
        wFile.writelines([str(n[-1])+" "+str(t)+"\n" for n,t in zip(msdAtom,tets)])
    else:
        wFile.write("msd$(AA^2)$\n")
        wFile.writelines([str(n[-1])+"\n" for n in msdAtom])
    wFile.close()
