#!/usr/bin/python
import sys

#mine
import poscarFixScale

def outcar2poscar(outcarF,outposF,wantconfig=-1,prompt=1):
    outcar = open(outcarF,"r")

    if wantconfig==0:
        print "Error: outcar2poscar: You must select a configuration >0, 0 is just POSCAR."
        exit(0)

    wdat="This poscar generated by outcar2poscar.py, from %s configuration #%d\n"%(outcarF,wantconfig)
    wdat+="1.0\n"

    while True:
        line=outcar.readline()
        if "ions per type" in line:
            nums=line.split("=")[1].strip()
            Natoms=sum(map(int,nums.split()))
        if "NSW" in line:
            nsteps=int(line.split()[2])
            break

    if wantconfig==-1:
        wantconfig=nsteps
    if wantconfig>nsteps:
        print "Error: outcar2poscar: Requested configuration >%d, the max configurations in OUTCAR."%nsteps
        exit(0)

    count=0
    while True:
        #Start a new configuration
        line=outcar.readline()
        if len(line)==0:
            break
        if "FORCE on cell" in line:
            count+=1
            if count!=wantconfig:
                continue
            while True:
                line=outcar.readline()
                if "direct lattice vectors" in line:
                    line=outcar.readline()
                    v1=" ".join(line.split()[0:3])
                    line=outcar.readline()
                    v2=" ".join(line.split()[0:3])
                    line=outcar.readline()
                    v3=" ".join(line.split()[0:3])
                    break

            while True:
                line=outcar.readline()
                if "POSITION" in line:
                    outcar.readline()
                    posi=list()
                    while True:
                        line=outcar.readline()
                        posi.append(" ".join(line.split()[0:3]))
                        if len(posi)==Natoms:
                            break
                    break
            break

    #Generate the rest of the poscar and write it out, make sure to correct for direct output
    if count>=0:
        wdat+=v1+"\n"
        wdat+=v2+"\n"
        wdat+=v3+"\n"
        wdat+=nums+"\n"
        wdat+="Direct\n"
        for i in posi:
            wdat+=i+"\n"

        open(outposF,"w").writelines(wdat)
        poscarFixScale.poscarFixScale(outposF,prompt)
    else:
        raise IOError("Unable to find desired POSCAR in OUTCAR.")

if __name__ == "__main__":
    if len(sys.argv)<3:
        print "Usage:"
        print sys.argv[0]+" <OUTCAR> <output poscar name> <desired config #, 0-indexed (default is last)>"
        exit(0)

    outcar=sys.argv[1]
    outposcar=sys.argv[2]

    if len(sys.argv)==4:
        wantconfig=int(sys.argv[3])
    else:
        wantconfig=-1 #last one by default

    outcar2poscar(outcar,outposcar,wantconfig)
