#!/usr/bin/python

import sys,os
import poscarIO

def usage():
    print "%s <element1> <element2> ... <elementN> <in:POSCAR-file> <out:XYZ-file>"%(sys.argv[0])

if len(sys.argv)<4:
    usage()
    exit(0)

elems=sys.argv[1:-2]
try:
    poscar=open(sys.argv[-2],"r").readlines()
    xyz=open(sys.argv[-1],"w")
except IOError:
    print "Error: Unable to open files."
    usage()
    exit(0)

[basis,atypes,atoms,head,poscar] = poscarIO.read(poscar)

N=sum(atypes)

data="%d\n"%N
data+="Generated by poscar2xyz.py from %s/%s\n"%(os.getcwd(),sys.argv[-2])
for ntype in range(len(atypes)):
    for i in range(atypes[ntype]):
        a=atoms.pop(0)
        data+="  %s\t%10.5f\t%10.5f\t%10.5f\n"%(elems[ntype],a[0],a[1],a[2])
xyz.write(data)
