#!/usr/bin/python

import sys
from numpy import *
#mine
import poscarIO
from lammpsIO import bounds2lohi
from struct_tools import flatten

def usage():
    print "%s <in:POSCAR-file> <out:LAMMPS config-file>"%(sys.argv[0].split("/")[-1])

if len(sys.argv)<3:
    usage()
    exit(0)

try:
    poscar=open(sys.argv[1],"r").readlines()
    lammps=open(sys.argv[2],"w")
except IOError:
    print "Error: Unable to open files."
    usage()
    exit(0)

[v1,v2,v3,atypes,ax,ay,az,head,poscar] = poscarIO.read(poscar,frac_coord=True)
atoms=zip(ax,ay,az)
#Convert from POSCAR style basis vectors to LAMMPS style boundaries.
bounds=[v1,v2,v3]
xhi,yhi,zhi,xy,xz,yz=bounds2lohi(bounds)

basis=matrix([[xhi,0,0],[xy,yhi,0],[xz,yz,zhi]])

N=sum(atypes)
Ntypes=len(atypes)
types=[i for i in flatten([[i]*v for i,v in enumerate(atypes)])]
data="#Generated by %s from %s\n\n"%(sys.argv[0].split("/")[-1],sys.argv[1])
data+="%d atoms\n"%N
data+="%d atom types\n\n"%Ntypes
data+="0.0000  %4f  xlo xhi\n"%xhi
data+="0.0000  %4f  ylo yhi\n"%yhi
data+="0.0000  %4f  zlo zhi\n"%zhi
data+="% 4f % 4f % 4f xy xz yz\n\n"%(xy,xz,yz)
data+="Atoms\n\n"
for i,(t,atom) in enumerate(zip(types,atoms)):
    x,y,z=(atom*basis).tolist()[0]
    data+="\t %d \t %d \t % 5f\t% 5f\t% 5f\n"%(i+1,t+1,x,y,z)
lammps.write(data)
lammps.close()
